#!/usr/bin/env bash

# Should grab the profile picture from /var/lib/AccountsService/icons/nekoking
# if not, return ~/.config/awesome/themes/neko-theme/profile.svg

themesDir="${HOME}/.config/awesome/themes"
accSerPic="/var/lib/AccountsService/icons/${USER}"

#if [ -f $accSerPic ];
#then
#	printf $accSerPic
#else
#	printf $profilePic
#fi

if [ -e "$themesDir/themeconfigs.txt" ]; then
	themeType=$(grep default: $themesDir/themeconfigs.txt | sed 's/default: //g')
	printf "$themesDir/$themeType/profile.svg"
else
	if [ -f $accSerPic ]; then
		printf $accSerPic
	else
		printf '$themesDir/neko-theme/profile.svg'
	fi
fi
