#!/usr/bin/env bash

# Should grab the profile picture from /var/lib/AccountsService/icons/nekoking
# if not, return ~/.config/awesome/themes/neko-theme/profile.svg

awesomeDir="${HOME}/.config/awesome/"
profilePic="${awesomeDir}/themes/neko-theme/profile.svg"
accSerPic="/var/lib/AccountsService/icons/${USER}"

if [ -f $accSerPic ];
then
	printf $accSerPic
else
	printf $profilePic
fi
